#!/usr/bin/env node
/**
 * Produce the tables in docs/study/analysis-plan.md from the exported CSVs.
 *
 *   node scripts/study/export-study-data.mjs --with-transcripts
 *   # score rubric_score in docs/study/results/tasks.csv by hand
 *   node scripts/study/analyse-study.mjs
 *
 * Writes docs/study/results/tables.md and prints the same to stdout.
 *
 * The reporting rules are enforced here rather than left to the writer:
 * counts and medians, never percentages, at n < 20; no significance test is run
 * automatically; and the pre-registered success criteria are evaluated exactly
 * as they were declared, whether or not they are met.
 */
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { OUT_DIR, writeText, median, range, counts, fmt } from './lib.mjs';

// ─── CSV reading ─────────────────────────────────────────────────────────────

function parseCsv(path) {
  if (!existsSync(path)) return [];
  const text = readFileSync(path, 'utf8').trim();
  if (!text) return [];
  const rows = [];
  let row = [], cell = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { cell += '"'; i++; }
      else if (c === '"') quoted = false;
      else cell += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(cell); cell = ''; }
    else if (c === '\n') { row.push(cell); rows.push(row); row = []; cell = ''; }
    else if (c !== '\r') cell += c;
  }
  if (cell || row.length) { row.push(cell); rows.push(row); }
  const [head, ...body] = rows;
  return body.map((r) => Object.fromEntries(head.map((h, i) => [h, r[i] ?? ''])));
}

const num = (v) => (v === '' || v === null || v === undefined ? null : Number(v));
const load = (name) => parseCsv(resolve(OUT_DIR, name));

const allSessions = load('sessions.csv');
const allTasks = load('tasks.csv');
const allSus = load('sus.csv');
const latency = load('latency.csv');

// Pre-registered exclusions (analysis-plan §2.2), applied once, here, and
// reported as counts. PLWD participants do one task per arm from a different,
// gentler list, so their times are not commensurable and protocol §3.1 says
// explicitly that they are not pooled.
const PRIMARY_GROUPS = new Set(['caregiver', 'worker']);
const sessions = allSessions.filter((s) => PRIMARY_GROUPS.has(s.group));
const plwd = allSessions.filter((s) => s.group === 'plwd');
const primaryCodes = new Set(sessions.map((s) => s.participant_code));
const primaryTasks = allTasks.filter((t) => primaryCodes.has(t.participant_code));
// A task cut short — the participant stopped the session while it was still open
// rather than ending the task — records a duration that is only a lower bound on
// how long they would have taken. Pooling those would bias every timing statistic
// downward, and would do it unevenly, because stopping is not random with respect
// to how hard the task was. Excluded once here rather than at each of the places
// duration is read, and reported as a count below.
const stoppedMidTask = primaryTasks.filter((t) => String(t.stopped_mid_task) === 'true');
const tasks = primaryTasks.filter((t) => String(t.stopped_mid_task) !== 'true');
const sus = allSus.filter((r) => primaryCodes.has(r.participant_code));

if (!allSessions.length) {
  console.error(`No sessions.csv in ${OUT_DIR}. Run scripts/study/export-study-data.mjs first.`);
  process.exit(1);
}

const out = [];
const say = (line = '') => { out.push(line); console.log(line); };

const ARMS = [['A', 'Arm A (avatar)'], ['B', 'Arm B (text)']];
const armTasks = (arm) => tasks.filter((t) => t.arm === arm);

// ─── Header ──────────────────────────────────────────────────────────────────

const complete = sessions.filter((s) => s.completed_both_arms === 'true');
say('# Study results — generated tables');
say('');
say('Generated by `scripts/study/analyse-study.mjs`. Table shells and reporting');
say('rules: `docs/study/analysis-plan.md`.');
say('');
say(`**Participants:** ${sessions.length} enrolled · ${complete.length} completed both arms`
  + ` · ${sessions.filter((s) => s.stopped_early === 'true').length} stopped early`);

const byGroup = counts(allSessions.map((s) => s.group));
say(`**Groups:** ${Object.entries(byGroup).map(([g, n]) => `${g} ${n}`).join(' · ')}`);
say('');
say(`**Excluded from the primary comparison:** ${plwd.length} participants living with`);
say('dementia (reported separately below — they complete a shortened, non-comparable');
say('protocol, per protocol §3.1).');
say('');
if (stoppedMidTask.length) {
  say(`**Tasks cut short by stopping, excluded from timing:** ${stoppedMidTask.length}.`);
  say('The participant stopped the session while the task was still open, so the recorded');
  say('duration is a lower bound rather than a time on task. Distinct from a task they');
  say('finished by saying they could not find the answer, counted separately below. The');
  say('turns inside those windows are still captured in the transcripts.');
  say('');
}
if (sessions.length < 20) {
  say('> n < 20, so everything below is counts and medians. No percentages, and no');
  say('> significance claim unless a test was run and met.');
  say('');
}

// ─── Table 1 — effectiveness ─────────────────────────────────────────────────

say('## Table 1 — Task success by arm');
say('');
const scored = tasks.filter((t) => t.rubric_score);
if (!scored.length) {
  say('_Not yet scored._ Fill `rubric_score` in `docs/study/results/tasks.csv` with');
  say('`complete` / `partial` / `failed`, against the rubric in `docs/study/tasks.md` §2.');
  say('');
} else {
  say('| | Complete | Partial | Failed | n tasks |');
  say('|---|---|---|---|---|');
  for (const [arm, label] of ARMS) {
    const c = counts(armTasks(arm).filter((t) => t.rubric_score).map((t) => t.rubric_score));
    say(`| ${label} | ${c.complete || 0} | ${c.partial || 0} | ${c.failed || 0} | ${armTasks(arm).filter((t) => t.rubric_score).length} |`);
  }
  say('');

  // Divergence between the rubric and the participant's own judgement. Reported
  // in both directions; over-reporting success on a partial answer is the one
  // that matters for a healthcare information tool.
  const over = scored.filter((t) => t.self_report === 'yes' && t.rubric_score !== 'complete');
  const under = scored.filter((t) => t.self_report === 'no' && t.rubric_score === 'complete');
  say(`**Self-report vs rubric.** ${over.length} tasks where the participant reported success`
    + ` on an answer the rubric did not score complete; ${under.length} the other way.`);
  if (over.length) {
    say('');
    say('> Worth discussing rather than reporting in passing: a participant who believes');
    say('> they found the answer when they did not is a trust finding for a healthcare');
    say('> information tool, not a scoring artefact.');
  }
  say('');
}

// ─── Table 2 — efficiency ────────────────────────────────────────────────────

say('## Table 2 — Time on task and turns');
say('');
say('| | Median time (s) | Min–max | Median turns | Min–max | n tasks |');
say('|---|---|---|---|---|---|');
const medTime = {};
for (const [arm, label] of ARMS) {
  const rows = armTasks(arm);
  const times = rows.map((t) => num(t.duration_s));
  const turns = rows.map((t) => num(t.turns));
  medTime[arm] = median(times);
  const [tlo, thi] = range(times);
  const [ulo, uhi] = range(turns);
  say(`| ${label} | ${fmt(medTime[arm])} | ${fmt(tlo)}–${fmt(thi)} | ${fmt(median(turns), 1)} | ${fmt(ulo)}–${fmt(uhi)} | ${rows.length} |`);
}
say('');

const pairs = pairedByParticipant(tasks);
say(`**Paired observations:** ${pairs.length} participants with a median time in both arms.`);
if (pairs.length >= 10) {
  say('');
  say('n ≥ 10 paired, so a Wilcoxon signed-rank test is admissible under the');
  say('pre-registered plan. It is **not run here** — run it deliberately, report the');
  say('statistic, the exact p and the n, and only then use the word "significant".');
} else {
  say('');
  say(`n = ${pairs.length} paired, below the pre-registered threshold of 10. Report`);
  say('descriptively; do not run a significance test.');
}
say('');

// ─── Table 3 — usability ─────────────────────────────────────────────────────

say('## Table 3 — SUS and Likert by arm');
say('');
say('| | Median SUS | Min–max | n | Trust | Engagement | Helpfulness | Clarity |');
say('|---|---|---|---|---|---|---|---|');
const medSus = {};
for (const [arm, label] of ARMS) {
  const rows = sus.filter((r) => r.arm === arm && r.sus !== '');
  const scores = rows.map((r) => num(r.sus));
  medSus[arm] = median(scores);
  const [lo, hi] = range(scores);
  const lk = (k) => fmt(median(sus.filter((r) => r.arm === arm).map((r) => num(r[k]))), 1);
  say(`| ${label} | ${fmt(medSus[arm], 1)} | ${fmt(lo, 1)}–${fmt(hi, 1)} | ${rows.length}`
    + ` | ${lk('trust')} | ${lk('engagement')} | ${lk('helpfulness')} | ${lk('clarity')} |`);
}
say('');
const partial = sus.filter((r) => r.sus === '' && r.answered !== '10');
if (partial.length) {
  say(`_${partial.length} SUS instruments were incomplete and are excluded — a SUS scored`);
  say('from fewer than ten items is not a SUS._');
  say('');
}

// ─── Order and set effects ───────────────────────────────────────────────────

say('## Order and set effects');
say('');
say('The Latin square exists to control these, so check that it did.');
say('');
say('| Cell | n tasks | Median time (s) |');
say('|---|---|---|');
for (const pos of ['1', '2']) {
  for (const [arm] of ARMS) {
    const rows = tasks.filter((t) => t.arm === arm && t.arm_position === pos);
    if (!rows.length) continue;
    say(`| Arm ${arm}, ${pos === '1' ? 'first' : 'second'} | ${rows.length} | ${fmt(median(rows.map((t) => num(t.duration_s))))} |`);
  }
}
say('');
say('| Task set | n tasks | Median time (s) |');
say('|---|---|---|');
for (const set of ['1', '2']) {
  const rows = tasks.filter((t) => t.set === set);
  if (!rows.length) continue;
  say(`| Set ${set} | ${rows.length} | ${fmt(median(rows.map((t) => num(t.duration_s))))} |`);
}
say('');

// ─── Table 4 — latency ───────────────────────────────────────────────────────

say('## Table 4 — Voice pipeline latency, live sessions');
say('');
const armA = latency.filter((r) => r.arm === 'A');
if (!armA.length) {
  say('_No instrumented Arm A turns._');
  say('');
} else {
  say('| Stage | Median (ms) | Min–max | n turns |');
  say('|---|---|---|---|');
  const STAGES = [
    ['stt_ms', 'Speech-to-text'],
    ['rag_ms', 'Retrieval'],
    ['llm_to_token_ms', 'LLM time to first token'],
    ['first_sentence_ms', 'First token → first sentence'],
    ['tts_first_ms', 'TTS request → audio received'],
    ['playback_wait_ms', 'Audio received → audio audible'],
    ['to_first_audio_ms', 'End to end → first avatar audio (audible)'],
  ];
  for (const [key, label] of STAGES) {
    const xs = armA.map((r) => num(r[key])).filter((x) => x !== null);
    if (!xs.length) continue;
    const [lo, hi] = range(xs);
    say(`| ${label} | ${fmt(median(xs))} | ${fmt(lo)}–${fmt(hi)} | ${xs.length} |`);
  }
  say('');
  const armB = latency.filter((r) => r.arm === 'B').map((r) => num(r.to_first_token_ms)).filter((x) => x !== null);
  if (armB.length) {
    say(`**Arm B, time to first token:** median ${fmt(median(armB))} ms over ${armB.length} turns —`);
    say('the text arm\'s analogue of end-to-end time to first audio.');
    say('');
  }
  say('Browsers, devices and networks varied between participants and were recorded');
  say('but not controlled. Text-to-speech ran over the **REST cascade**, not the');
  say('WebSocket streaming path, so these are not comparable to the figures in');
  say('`docs/voice-latency-streaming.md` (`docs/study/protocol.md` §10.4).');
  say('');
}

// ─── Reliability ─────────────────────────────────────────────────────────────

say('## Reliability and fallbacks');
say('');
say('Interpretation guard: a low Arm A usability score alongside a high fallback');
say('count is a reliability finding, not an avatar finding.');
say('');
const browsers = counts(sessions.map((s) => s.browser).filter(Boolean));
say(`**Browsers:** ${Object.entries(browsers).map(([b, n]) => `${b} ${n}`).join(' · ') || '—'}`);

const renderers = counts(sessions.map((s) => s.renderer).filter(Boolean));
say(`**Avatar renderer:** ${Object.entries(renderers).map(([r, n]) => `${r} ${n}`).join(' · ') || '—'}`);
if (Object.keys(renderers).length > 1) {
  say('');
  say('> **Participants did not all see the same avatar.** Some sessions degraded to');
  say('> the Three.js fallback. Arm A results cannot be pooled across renderers');
  say('> without saying so — report the split and, if the counts allow, the Arm A');
  say('> usability scores separately.');
}
const gaveUp = tasks.filter((t) => t.gave_up === 'true').length;
say(`**Tasks abandoned ("I couldn't find it"):** ${gaveUp} of ${tasks.length}`);
say('');

const fb = load('fallbacks.csv');
if (fb.length) {
  say('| Fallback | Arm A | Arm B |');
  say('|---|---|---|');
  for (const kind of [...new Set(fb.map((f) => f.kind))].sort()) {
    const n = (arm) => fb.filter((f) => f.kind === kind && f.arm === arm).length;
    say(`| ${kind} | ${n('A')} | ${n('B')} |`);
  }
  say('');
} else {
  say('_No fallback events recorded._');
  say('');
}

const walkedAway = tasks.filter((t) => num(t.hidden_ms) > 30000);
if (walkedAway.length) {
  say(`**Tasks with the tab hidden for over 30 s:** ${walkedAway.length}. Time on task is a`);
  say('wall clock, so these inflate it. Decide whether to exclude them **before** looking');
  say('at what that does to the result, and report the decision either way.');
  say('');
}

if (plwd.length) {
  say('## Participants living with dementia — reported separately');
  say('');
  say(`${plwd.length} participants, shortened protocol (one task per arm, plain-language`);
  say('questions in place of SUS). Not pooled above: the task list and the instruments');
  say('differ, so the numbers are not commensurable.');
  say('');
  const pTasks = allTasks.filter((t) => !primaryCodes.has(t.participant_code));
  say('| | n tasks | Median time (s) | Completed |');
  say('|---|---|---|---|');
  for (const [arm, label] of ARMS) {
    const rows = pTasks.filter((t) => t.arm === arm);
    if (!rows.length) continue;
    say(`| ${label} | ${rows.length} | ${fmt(median(rows.map((t) => num(t.duration_s))))}`
      + ` | ${rows.filter((t) => t.rubric_score === 'complete').length} |`);
  }
  say('');
  say('Plain-language responses are in `responses.csv` under `likert.*`; the support');
  say('person\'s answers are under `supporter.*`. Report thematically.');
  say('');
}

say('## Role contrast — descriptive only');
say('');
say('Analysis-plan §4.1. n is far too small for an interaction test.');
say('');
say('| Group | n | Median time A (s) | Median time B (s) | Median SUS A | Median SUS B |');
say('|---|---|---|---|---|---|');
for (const g of ['caregiver', 'worker']) {
  const codes = new Set(sessions.filter((x) => x.group === g).map((x) => x.participant_code));
  if (!codes.size) continue;
  const t = (arm) => median(tasks.filter((x) => codes.has(x.participant_code) && x.arm === arm).map((x) => num(x.duration_s)));
  const u = (arm) => median(sus.filter((x) => codes.has(x.participant_code) && x.arm === arm).map((x) => num(x.sus)));
  say(`| ${g} | ${codes.size} | ${fmt(t('A'))} | ${fmt(t('B'))} | ${fmt(u('A'), 1)} | ${fmt(u('B'), 1)} |`);
}
say('');

// Self-selection is a named threat in analysis-plan §7: volunteers for a
// technology study are more technology-confident than the target population.
// Report the distribution rather than assuming it away.
const responses = load('responses.csv');
const conf = responses.filter((r) => r.key === 'tech_confidence' && primaryCodes.has(r.participant_code));
if (conf.length) {
  const dist = counts(conf.map((r) => r.value));
  say('**Self-rated confidence with apps and websites (1–5):** '
    + Object.entries(dist).sort().map(([v, n]) => `${v}: ${n}`).join(' · '));
  say('');
  say('A skew toward 4–5 is the self-selection threat in analysis-plan §7 showing up in');
  say('the data. Report it; do not adjust for it.');
  say('');
}

// ─── Success criteria ────────────────────────────────────────────────────────

say('## Pre-registered success criteria');
say('');
say('Declared in `docs/study/protocol.md` §7.1 before data collection.');
say('');
say('| Criterion | Target | Result | Met? |');
say('|---|---|---|---|');

const likertA = ['trust', 'engagement', 'helpfulness', 'clarity']
  .map((k) => median(sus.filter((r) => r.arm === 'A').map((r) => num(r[k]))))
  .filter((x) => x !== null);
const meanLikertA = likertA.length ? likertA.reduce((a, b) => a + b, 0) / likertA.length : null;
const usabilityMet = medSus.A !== null && medSus.A >= 68 && meanLikertA !== null && meanLikertA >= 4;
say(`| Usability | SUS ≥ 68 and mean Likert ≥ 4 on Arm A | SUS ${fmt(medSus.A, 1)}, Likert ${fmt(meanLikertA, 2)} | ${verdict(medSus.A !== null && meanLikertA !== null, usabilityMet)} |`);

// Paired, per analysis-plan §3.2: the design is within-subjects, so the unit is
// the participant. Pooling task rows also inflates the apparent n from ~12
// participants to ~72 tasks.
const pairedA = median(pairs.map((p) => p.a));
const pairedB = median(pairs.map((p) => p.b));
let reduction = null;
if (pairedA !== null && pairedB !== null && pairedB > 0) {
  reduction = ((pairedB - pairedA) / pairedB) * 100;
}
const efficiencyMet = reduction !== null && reduction >= 30;
// Direction in words. A bare "-42.9 %" under a heading reading "≥30 % lower"
// invites being read as "42.9 % lower" — backwards, and in exactly the direction
// the protocol warns is most likely.
const efficiencyText = reduction === null
  ? '—'
  : reduction >= 0
    ? `Arm A ${fmt(reduction, 1)} % faster`
    : `Arm A ${fmt(Math.abs(reduction), 1)} % slower`;
say(`| Efficiency | ≥ 30 % lower median time, Arm A vs B | ${efficiencyText} (paired, n = ${pairs.length}) | ${verdict(reduction !== null, efficiencyMet)} |`);
say('| Safety | Zero safety-gate hits across all transcripts | run `safety-scan-transcripts.mjs` | — |');
say('');

if (reduction !== null && !efficiencyMet) {
  say('> **The efficiency criterion was not met.** This was flagged in advance as the');
  say('> most likely of the three to fail, and a null or reversed result here is a');
  say('> legitimate finding — spoken answers are consumed at speaking rate, and the');
  say('> text path streams its first token sooner. Report it plainly. Do not retreat');
  say('> to a claim the data does not support: "preferred" or "more accessible"');
  say('> without "faster" is defensible **only** if the usability and qualitative');
  say('> data actually show it.');
  say('');
}

say('---');
say('');
say('Still to do by hand: rubric scoring (`docs/study/tasks.md` §2), the transcript');
say('safety scan, and the thematic analysis of the debrief answers');
say('(`docs/study/analysis-plan.md` §4.4).');

const path = writeText('tables.md', out.join('\n'));
console.log('');
console.log(`Written to ${path}`);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function verdict(measurable, met) {
  if (!measurable) return 'not yet measurable';
  return met ? '**yes**' : 'no';
}

/** Participants with a median time in both arms — the design is within-subjects,
 *  so the comparison is paired. */
function pairedByParticipant(rows) {
  const by = new Map();
  for (const r of rows) {
    const t = num(r.duration_s);
    if (t === null) continue;
    if (!by.has(r.participant_code)) by.set(r.participant_code, { A: [], B: [] });
    by.get(r.participant_code)[r.arm]?.push(t);
  }
  return [...by.entries()]
    .filter(([, v]) => v.A.length && v.B.length)
    .map(([code, v]) => ({ code, a: median(v.A), b: median(v.B) }));
}
